### ISSUE TITLE
Create Account/Sign In - Cannot read property 'pathname' of undefined.

### ISSUE THREAD

**Issue by jaynimble** [digifi-io/loan-origination-system#47]
Hi there,

When creating an account, I enter the details as expected but when I hit submit, I get an error:

```
Cannot read property 'pathname' of undefined TypeError: Cannot read property 'pathname' of undefined
    at /Users//Development/Experimental/loan-origination-system/content/container/decision-engine-service-container/controllers/transform.js:14:81
    at Layer.handle [as handle_request] (/Users//Development/Experimental/loan-origination-system/node_modules/express/lib/router/layer.js:95:5)
```
I put a break point on the offending line, and I could see that the expected variable of _parsedOriginalUrl was indeed undefined on the req type:

`let transformsFilters = (transformType[req.method]) ?
    helpers.findMatchingRoute(transformType[req.method], req._parsedOriginalUrl.pathname) :
    false;`

I noticed that there as a valid _parsedUrl variable so I updated the code to reference that variable instead of the 'Original' one and I was able to create an account and sign in but whenever I go to any of the areas like ML or Decisioning or Accounts, it returns a 404 error message.

I don't know if my fix is valid as I may have an underlying issue in my configuration. Any help you can give is much appreciated.

**Comment by jaynimble** [comment]
Something else I noticed is that when I do log in, I get the following error:

`2019-10-26T07:55:11.159Z - error: Cannot set property 'userprivilegesdata' of undefined TypeError: Cannot set property 'userprivilegesdata' of undefined
    at Object.setPrivilegesOnUser (/Users/jasonbarry/Development/Experimental/loan-origination-system/node_modules/periodicjs.ext.user_access_control/utilities/privilege.js:129:34)
    at /Users/jasonbarry/Development/Experimental/loan-origination-system/node_modules/periodicjs.ext.user_access_control/controllers/uac.js:19:49
    at processTicksAndRejections (internal/process/task_queues.js:89:5) 
{
  err: {},
`

Which may explain why I can't access anything.

**Comment by codhah92** [comment]
Hi @jaynimble,

This is an issue that some other users have run into before, and there is a resolved ticket here that you can use as a guideline to fix it: https://github.com/digifi-io/loan-origination-system/issues/17 . The general idea is that you need Redis to be running locally to have the login functionality work properly, and in addition, you will need to make sure that your Redis configuration in your mongo configuration documents are properly setup. You shouldn't have to update any of the code to get the system up and running, so if you run into issues, it's usually due to some type of configuration/installation issue!

Hopefully that helps!
